from dataclasses import dataclass
from enum import Enum

from core.events import ControllerEvent


class Action(Enum):
    DECK_1_PLAY_TOGGLE = "DECK_1_PLAY_TOGGLE"
    DECK_2_PLAY_TOGGLE = "DECK_2_PLAY_TOGGLE"

    DECK_1_CUE = "DECK_1_CUE"
    DECK_2_CUE = "DECK_2_CUE"

    DECK_1_SYNC = "DECK_1_SYNC"
    DECK_2_SYNC = "DECK_2_SYNC"

    DECK_1_LOAD_TRACK = "DECK_1_LOAD_TRACK"
    DECK_2_LOAD_TRACK = "DECK_2_LOAD_TRACK"

    BROWSER_UP = "BROWSER_UP"
    BROWSER_DOWN = "BROWSER_DOWN"
    BROWSER_LEVEL_UP = "BROWSER_LEVEL_UP"
    BROWSER_LEVEL_DOWN = "BROWSER_LEVEL_DOWN"

    TOGGLE_ACTIVE_DECK = "TOGGLE_ACTIVE_DECK"

    ACTIVE_DECK_HOTCUE_PREVIOUS = "ACTIVE_DECK_HOTCUE_PREVIOUS"
    ACTIVE_DECK_HOTCUE_NEXT = "ACTIVE_DECK_HOTCUE_NEXT"
    ACTIVE_DECK_HOTCUE_TOGGLE = "ACTIVE_DECK_HOTCUE_TOGGLE"

    DECK_1_HOTCUE_PREVIOUS = "DECK_1_HOTCUE_PREVIOUS"
    DECK_1_HOTCUE_NEXT = "DECK_1_HOTCUE_NEXT"
    DECK_1_HOTCUE_TOGGLE = "DECK_1_HOTCUE_TOGGLE"

    DECK_2_HOTCUE_PREVIOUS = "DECK_2_HOTCUE_PREVIOUS"
    DECK_2_HOTCUE_NEXT = "DECK_2_HOTCUE_NEXT"
    DECK_2_HOTCUE_TOGGLE = "DECK_2_HOTCUE_TOGGLE"

    DECK_1_LOOP_SIZE_DECREASE = "DECK_1_LOOP_SIZE_DECREASE"
    DECK_1_LOOP_SIZE_INCREASE = "DECK_1_LOOP_SIZE_INCREASE"
    DECK_1_LOOP_TOGGLE = "DECK_1_LOOP_TOGGLE"

    DECK_2_LOOP_SIZE_DECREASE = "DECK_2_LOOP_SIZE_DECREASE"
    DECK_2_LOOP_SIZE_INCREASE = "DECK_2_LOOP_SIZE_INCREASE"
    DECK_2_LOOP_TOGGLE = "DECK_2_LOOP_TOGGLE"

    DECK_1_BPM_INCREASE = "DECK_1_BPM_INCREASE"
    DECK_1_BPM_DECREASE = "DECK_1_BPM_DECREASE"

    DECK_2_BPM_INCREASE = "DECK_2_BPM_INCREASE"
    DECK_2_BPM_DECREASE = "DECK_2_BPM_DECREASE"

    ACTIVE_DECK_SEEK_BACKWARD = "ACTIVE_DECK_SEEK_BACKWARD"
    ACTIVE_DECK_SEEK_FORWARD = "ACTIVE_DECK_SEEK_FORWARD"

    DECK_1_SEEK_BACKWARD = "DECK_1_SEEK_BACKWARD"
    DECK_1_SEEK_FORWARD = "DECK_1_SEEK_FORWARD"

    DECK_2_SEEK_BACKWARD = "DECK_2_SEEK_BACKWARD"
    DECK_2_SEEK_FORWARD = "DECK_2_SEEK_FORWARD"

    CYCLE_SEEK_SPEED = "CYCLE_SEEK_SPEED"

    FEEDBACK_ACTIVE_DECK_1 = "FEEDBACK_ACTIVE_DECK_1"
    FEEDBACK_ACTIVE_DECK_2 = "FEEDBACK_ACTIVE_DECK_2"


@dataclass(frozen=True)
class ActionEvent:
    action: Action
    value: float
    source_event: ControllerEvent
