from dataclasses import dataclass
from enum import Enum

from core.events import ControllerEvent


class Action(Enum):
    DECK_1_PLAY_TOGGLE = "DECK_1_PLAY_TOGGLE"
    DECK_2_PLAY_TOGGLE = "DECK_2_PLAY_TOGGLE"

    DECK_1_CUE = "DECK_1_CUE"
    DECK_2_CUE = "DECK_2_CUE"

    DECK_1_SYNC = "DECK_1_SYNC"
    DECK_2_SYNC = "DECK_2_SYNC"

    DECK_1_LOAD_TRACK = "DECK_1_LOAD_TRACK"
    DECK_2_LOAD_TRACK = "DECK_2_LOAD_TRACK"

    BROWSER_UP = "BROWSER_UP"
    BROWSER_DOWN = "BROWSER_DOWN"
    BROWSER_LEVEL_UP = "BROWSER_LEVEL_UP"
    BROWSER_LEVEL_DOWN = "BROWSER_LEVEL_DOWN"

    BROWSER_TREE_UP = "BROWSER_TREE_UP"
    BROWSER_TREE_DOWN = "BROWSER_TREE_DOWN"

    BROWSER_LIST_UP = "BROWSER_LIST_UP"
    BROWSER_LIST_DOWN = "BROWSER_LIST_DOWN"
    BROWSER_TREE_COLLAPSE = "BROWSER_TREE_COLLAPSE"
    BROWSER_TREE_EXPAND = "BROWSER_TREE_EXPAND"

    TOGGLE_ACTIVE_DECK = "TOGGLE_ACTIVE_DECK"

    ACTIVE_DECK_HOTCUE_PREVIOUS = "ACTIVE_DECK_HOTCUE_PREVIOUS"
    ACTIVE_DECK_HOTCUE_NEXT = "ACTIVE_DECK_HOTCUE_NEXT"
    ACTIVE_DECK_HOTCUE_TOGGLE = "ACTIVE_DECK_HOTCUE_TOGGLE"

    DECK_1_HOTCUE_PREVIOUS = "DECK_1_HOTCUE_PREVIOUS"
    DECK_1_HOTCUE_NEXT = "DECK_1_HOTCUE_NEXT"
    DECK_1_HOTCUE_TOGGLE = "DECK_1_HOTCUE_TOGGLE"

    DECK_2_HOTCUE_PREVIOUS = "DECK_2_HOTCUE_PREVIOUS"
    DECK_2_HOTCUE_NEXT = "DECK_2_HOTCUE_NEXT"
    DECK_2_HOTCUE_TOGGLE = "DECK_2_HOTCUE_TOGGLE"

    DECK_1_LOOP_SIZE_DECREASE = "DECK_1_LOOP_SIZE_DECREASE"
    DECK_1_LOOP_SIZE_INCREASE = "DECK_1_LOOP_SIZE_INCREASE"
    DECK_1_LOOP_TOGGLE = "DECK_1_LOOP_TOGGLE"

    DECK_2_LOOP_SIZE_DECREASE = "DECK_2_LOOP_SIZE_DECREASE"
    DECK_2_LOOP_SIZE_INCREASE = "DECK_2_LOOP_SIZE_INCREASE"
    DECK_2_LOOP_TOGGLE = "DECK_2_LOOP_TOGGLE"

    DECK_1_BPM_INCREASE = "DECK_1_BPM_INCREASE"
    DECK_1_BPM_DECREASE = "DECK_1_BPM_DECREASE"

    DECK_2_BPM_INCREASE = "DECK_2_BPM_INCREASE"
    DECK_2_BPM_DECREASE = "DECK_2_BPM_DECREASE"

    ACTIVE_DECK_SEEK_BACKWARD = "ACTIVE_DECK_SEEK_BACKWARD"
    ACTIVE_DECK_SEEK_FORWARD = "ACTIVE_DECK_SEEK_FORWARD"

    DECK_1_SEEK_FINE_BACKWARD = "DECK_1_SEEK_FINE_BACKWARD"
    DECK_1_SEEK_FINE_FORWARD = "DECK_1_SEEK_FINE_FORWARD"
    DECK_1_SEEK_4_BARS_BACKWARD = "DECK_1_SEEK_4_BARS_BACKWARD"
    DECK_1_SEEK_4_BARS_FORWARD = "DECK_1_SEEK_4_BARS_FORWARD"
    DECK_1_SEEK_8_BARS_BACKWARD = "DECK_1_SEEK_8_BARS_BACKWARD"
    DECK_1_SEEK_8_BARS_FORWARD = "DECK_1_SEEK_8_BARS_FORWARD"

    DECK_2_SEEK_FINE_BACKWARD = "DECK_2_SEEK_FINE_BACKWARD"
    DECK_2_SEEK_FINE_FORWARD = "DECK_2_SEEK_FINE_FORWARD"
    DECK_2_SEEK_4_BARS_BACKWARD = "DECK_2_SEEK_4_BARS_BACKWARD"
    DECK_2_SEEK_4_BARS_FORWARD = "DECK_2_SEEK_4_BARS_FORWARD"
    DECK_2_SEEK_8_BARS_BACKWARD = "DECK_2_SEEK_8_BARS_BACKWARD"
    DECK_2_SEEK_8_BARS_FORWARD = "DECK_2_SEEK_8_BARS_FORWARD"

    # Layer 2 – Mixer / EQ
    DECK_1_VOLUME = "DECK_1_VOLUME"
    DECK_2_VOLUME = "DECK_2_VOLUME"

    DECK_1_EQ_ADJUST = "DECK_1_EQ_ADJUST"
    DECK_2_EQ_ADJUST = "DECK_2_EQ_ADJUST"

    DECK_1_EQ_HIGH = "DECK_1_EQ_HIGH"
    DECK_1_EQ_MID_HIGH = "DECK_1_EQ_MID_HIGH"
    DECK_1_EQ_MID_LOW = "DECK_1_EQ_MID_LOW"
    DECK_1_EQ_LOW = "DECK_1_EQ_LOW"

    DECK_2_EQ_HIGH = "DECK_2_EQ_HIGH"
    DECK_2_EQ_MID_HIGH = "DECK_2_EQ_MID_HIGH"
    DECK_2_EQ_MID_LOW = "DECK_2_EQ_MID_LOW"
    DECK_2_EQ_LOW = "DECK_2_EQ_LOW"

    # EQ-Band Auswahl per Stick-Y
    DECK_1_EQ_BAND_UP = "DECK_1_EQ_BAND_UP"
    DECK_1_EQ_BAND_DOWN = "DECK_1_EQ_BAND_DOWN"

    DECK_2_EQ_BAND_UP = "DECK_2_EQ_BAND_UP"
    DECK_2_EQ_BAND_DOWN = "DECK_2_EQ_BAND_DOWN"

    # Klick auf Stick = aktuelles Band Kill/On-Off
    TOGGLE_DECK_1_EQ_BAND = "TOGGLE_DECK_1_EQ_BAND"
    TOGGLE_DECK_2_EQ_BAND = "TOGGLE_DECK_2_EQ_BAND"

    # Konkrete MIDI-Actions für Kill
    DECK_1_EQ_HIGH_TOGGLE = "DECK_1_EQ_HIGH_TOGGLE"
    DECK_1_EQ_MID_HIGH_TOGGLE = "DECK_1_EQ_MID_HIGH_TOGGLE"
    DECK_1_EQ_MID_LOW_TOGGLE = "DECK_1_EQ_MID_LOW_TOGGLE"
    DECK_1_EQ_LOW_TOGGLE = "DECK_1_EQ_LOW_TOGGLE"

    DECK_2_EQ_HIGH_TOGGLE = "DECK_2_EQ_HIGH_TOGGLE"
    DECK_2_EQ_MID_HIGH_TOGGLE = "DECK_2_EQ_MID_HIGH_TOGGLE"
    DECK_2_EQ_MID_LOW_TOGGLE = "DECK_2_EQ_MID_LOW_TOGGLE"
    DECK_2_EQ_LOW_TOGGLE = "DECK_2_EQ_LOW_TOGGLE"

    # Layer 2 – Gain
    DECK_1_GAIN_DECREASE = "DECK_1_GAIN_DECREASE"
    DECK_1_GAIN_INCREASE = "DECK_1_GAIN_INCREASE"

    DECK_2_GAIN_DECREASE = "DECK_2_GAIN_DECREASE"
    DECK_2_GAIN_INCREASE = "DECK_2_GAIN_INCREASE"

    # Layer 2 – Mixer FX Deck A
    MIXER_FX_A_AMOUNT_DECREASE = "MIXER_FX_A_AMOUNT_DECREASE"
    MIXER_FX_A_AMOUNT_INCREASE = "MIXER_FX_A_AMOUNT_INCREASE"

    MIXER_FX_A_PREVIOUS = "MIXER_FX_A_PREVIOUS"
    MIXER_FX_A_NEXT = "MIXER_FX_A_NEXT"

    MIXER_FX_A_LOAD = "MIXER_FX_A_LOAD"
    MIXER_FX_A_TOGGLE = "MIXER_FX_A_TOGGLE"

    # Layer 2 – Mixer FX Deck B
    MIXER_FX_B_AMOUNT_DECREASE = "MIXER_FX_B_AMOUNT_DECREASE"
    MIXER_FX_B_AMOUNT_INCREASE = "MIXER_FX_B_AMOUNT_INCREASE"

    MIXER_FX_B_PREVIOUS = "MIXER_FX_B_PREVIOUS"
    MIXER_FX_B_NEXT = "MIXER_FX_B_NEXT"

    MIXER_FX_B_LOAD = "MIXER_FX_B_LOAD"
    MIXER_FX_B_TOGGLE = "MIXER_FX_B_TOGGLE"

    MIXER_FX_A_AMOUNT = "MIXER_FX_A_AMOUNT"
    MIXER_FX_B_AMOUNT = "MIXER_FX_B_AMOUNT"

    TOGGLE_MIXER_FX_A_DIRECTION = "TOGGLE_MIXER_FX_A_DIRECTION"
    TOGGLE_MIXER_FX_B_DIRECTION = "TOGGLE_MIXER_FX_B_DIRECTION"

    CYCLE_SEEK_SPEED = "CYCLE_SEEK_SPEED"

    FEEDBACK_ACTIVE_DECK_1 = "FEEDBACK_ACTIVE_DECK_1"
    FEEDBACK_ACTIVE_DECK_2 = "FEEDBACK_ACTIVE_DECK_2"

    SELECT_MIXER_FX_DECK_A = "SELECT_MIXER_FX_DECK_A"
    SELECT_MIXER_FX_DECK_B = "SELECT_MIXER_FX_DECK_B"


@dataclass(frozen=True)
class ActionEvent:
    action: Action
    value: float
    source_event: ControllerEvent
