# DualShock 4
SONY_VENDOR_ID = 0x054C
DUALSHOCK_4_PRODUCT_ID = 0x05C4

BLUETOOTH_INPUT_REPORT_ID = 0x11
BLUETOOTH_OUTPUT_REPORT_ID = 0x11
BLUETOOTH_REPORT_SIZE = 78
BLUETOOTH_OUTPUT_CRC_SEED = 0xA2
BLUETOOTH_HARDWARE_CONTROL = 0xC4

# Analogsticks
STICK_CENTER = 128
STICK_NEGATIVE_RANGE = 128
STICK_POSITIVE_RANGE = 127
STICK_DEADZONE = 15

# Event-Erkennung
BUTTON_HOLD_THRESHOLD = 0.5
BUTTON_DOUBLE_PRESS_THRESHOLD = 0.3

AXIS_CHANGE_THRESHOLD = 0.05
AXIS_TRIGGER_THRESHOLD = 0.9
AXIS_RELEASE_THRESHOLD = 0.4

# Touchpad
TOUCHPAD_MAX_X = 1919
TOUCHPAD_MAX_Y = 941

SWIPE_DISTANCE_THRESHOLD = 180
SWIPE_AXIS_DOMINANCE = 1.25

# Performance
SEEK_SPEEDS = (1, 4, 16)
